### ISSUE TITLE
How to deal with slice of pointers

### ISSUE THREAD

**Issue by voidint** [koss-null/FuncFrog#10]
```go
package main

import (
	"fmt"

	"github.com/koss-null/funcfrog/pkg/pipe"
)

type Student struct {
	Number uint32
	Name   string
}

func main() {
	items := []*Student{
		{Number: 10000, Name: "Tom"},
		{Number: 10001, Name: "Jerry"},
	}

	item := pipe.Slice(items).
		Filter(pipe.Pred(func(item *Student) bool {
			return item.Number > 10000
		})).
		First()

	fmt.Println(item, *item, **item)
}

```

**Comment by koss-null** [comment]
Hi! It looks like you need a double pointer on predicate reciever here. Filter expects the type in the predicate to be a pointer on your slice type wich is *Student itself. 
Also you may use FuncP initialization and return *Student[i] from there.

**Comment by koss-null** [comment]
> ```go
> item := pipe.
> 	Fn(func(i int) *Student {
> 		return items[i]
> 	}).
> 	Gen(len(items)).
> 	Filter(pipe.Pred(func(s *Student) bool {
> 		return s.Number > 10000
> 	})).
> 	First()
> ```
> 
> Is that right? But it feels a little complicated.

Not quite. This is the wright way https://play.golang.com/p/649_akFwmug
Also you don't need to explicitly convert to pipe.Pred, you just send the function as is.
